### PR TITLE
feature: add custom avatar ability in search

### PR DESCRIPTION
**Pull request by adrianthedev**
This allows users to add the external image as a [custom Avatar](https://nova.laravel.com/docs/2.0/resources/fields.html#avatar-field) in searches.

### CODE REVIEW

**Comment by adrianthedev** [comment]
Does this look good to you @chaseconey?

**Comment by adrianthedev** [comment]
Did you have any time to look into this PR @chaseconey?

**Review by chaseconey — APPROVED** [review]

**Comment by chaseconey** [comment]
Thanks @adrianthedev

**Comment by adrianthedev** [comment]
Yeah, for sure!

Can I bother you to cut a release too?

**Comment by chaseconey** [comment]
@adrianthedev sorry about that, I swear I did it, but I _was_ multi-tasking... :D

**Pull request merged**
